# Generated by Django 4.0.2 on 2023-05-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='categories',
        ),
    ]
